baseURL = 'https://bjonnh.github.io/fpga_class_psone'
canonifyURLs = true
relativeURLs = true

languageCode = 'en-us'
title = 'PS1 FPGA Class'


[module]
[[module.imports]]
  path = 'github.com/McShelby/hugo-theme-relearn'


theme = "hugo-theme-relearn"
[params]
  themeVariant = ["neon", "relearn-light", "relearn-dark", "blue"]
  showVisitedLinks = true


[outputs]
home = [ "HTML", "RSS", "SEARCH", "PRINT", "SEARCHPAGE"]

